services:
  - type: web
    name: classtrack-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /health
    disk:
      name: classtrack-data
      mountPath: /app/data
      sizeGB: 1